language: python
python:
  - "2.7"
  
sudo: required
dist: trusty

before_install:
  - sudo apt-get install -y postgresql-9.5-postgis-2.2 postgresql-9.5-postgis-scripts postgis

# command to install dependencies
install:
  - "pip install -r requirements.txt --use-mirrors"

# database creation
before_script:
  - psql -c 'create database travis_postgis;' -U postgres
  - psql -c 'CREATE EXTENSION postgis;' -U postgres -d travis_postgis
  - psql -c 'CREATE EXTENSION postgis_topology;' -U postgres -d travis_postgis
  - psql -f test_data.sql -U postgres -d travis_postgis

# command to run tests
script: nosetests --verbose
