language: python
python:
  - "2.7"
  
sudo: required
dist: trusty

before_install:
  - sudo apt-get install -y postgresql-9.5-postgis-2.2 postgresql-9.5-postgis-2.2-scripts

# command to install dependencies
install:
  - "pip install -r requirements.txt"

# database creation
before_script:
  - psql -c "create database travis_postgis;" -U postgres
  - psql -c "CREATE EXTENSION postgis version '2.2.2';" -U postgres -d travis_postgis
  - psql -c "CREATE EXTENSION postgis_topology version '2.2.2';" -U postgres -d travis_postgis
  - psql -f test_data.sql -U postgres -d travis_postgis

# command to run tests
script: nosetests --verbose
